### ISSUE TITLE
Jak utworzyć tekst w nowej linijce

### ISSUE THREAD

**Issue by mateuszanierusza** [DreamPoland/dream-otchlan#29]
Fajnie jakby można było dać więcej linijek tekstu nie w tej samej linii tylko pod spodem jako kolejna wiadomość, mniej więcej jak pokazałem niżej. Bo próbowałem na wszystkie sposoby to ogarnąć ale nie idzie i po prostu drugiej wiadomości nie odczytuje bądź ją usuwa czasami

![image](https://user-images.githubusercontent.com/59318217/233171925-4c1a212a-08f3-4874-8603-e1f40ff1366f.png)

**Comment by Ravis96** [comment]
Sory, że tak długo czekasz na odpowiedz - Szybiej odpowiadamy na discord. Jeśli potrzebujesz następnej linijki, to musisz użyć ``%NEWLINE%`` pomiędzy dwoma wiadomościami.

**Comment by mateuszanierusza** [comment]
Dziękuje <3

Jeszcze jeden problem jest, że czasami tekst się podwaja, nawet jak jest mini lag to wiadomość potrafi wysłać podwójnie

**Comment by Ravis96** [comment]
> Dziękuje <3
> 
> Jeszcze jeden problem jest, że czasami tekst się podwaja, nawet jak jest mini lag to wiadomość potrafi wysłać podwójnie

Znam problem, poprawie to na dniach w miarę wolnego czasu.

**Comment by mateuszanierusza** [comment]
dziękuje, a tak poza tym to plugin kozacki dobra robota
